modules: switch to tinyusb 0.14.0
greatscottgadgets/apollo pull request #13
Opened 2023-02-03 22:18 UTC by cyber-murmel

Switch to TinyUSB 0.14.0

updates lib/tinyusb submodule to 0.14.0 and adapts board source files accordingly
firmware for daisho couldn't be build to to missing bsp in TinyUSB

current TinyUSB submodule makes building for ESP32-S2 quite hard

2023-03-30 14:53 UTC, mossmann requested changes
Thank you for the contribution! I've requested a change that seemed to be necessary in my tests.

Additionally I had trouble completing my tests because the binary size when building for Cynthion (hardware formerly known as LUNA) exceeds the available flash (when installed with a 4 kB bootloader). Have you tried building for Cynthion, and do you have any ideas for how to reduce the binary size?

2023-04-01 20:59 UTC, cyber-murmel commented
I have only built for other targets to check that the build process didn't break, since I don't have any Cynthion device. The PR is a back port of another branch where I added other devices.

What is the correct `APOLLO_BOARD` for Cynthion?

Apparently the compiler already optimizes for least space, since `-Os` doesn't change anything and all other optimization options make the linker fail to fit it in rom.
Also removing `-g` didn't make a difference...
Does it fail for you every time regardless of optimization and debug flags?

May I ask what gcc vesion you use?
Mine is
```
$ arm-none-eabi-gcc --version
arm-none-eabi-gcc (Arm GNU Toolchain 11.3.Rel1) 11.3.1 20220712
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

2023-04-01 21:03 UTC, cyber-murmel commented
If you want a reproducible build environment, this is my current `shell.nix`

```nix
{ pkgs ? import
    (builtins.fetchGit {
      name = "nixos-22.11-2023_04_01";
      url = "https://github.com/nixos/nixpkgs/";
      ref = "refs/heads/nixos-22.11";
      rev = "a575c243c23e2851b78c00e9fa245232926ec32f";
    })
    { }
}:

with pkgs;

mkShell {
  buildInputs = [
    gcc
    gcc-arm-embedded
    gnumake
    dfu-util
    udisks
    python3Packages.pyserial
  ];
}
```

2023-06-28 17:07 UTC, mossmann commented
@cyber-murmel Thank you so much for looking into this further! We've managed to make size improvements in #17 and by reducing the size of Saturn-V from 4 KiB to 2 KiB (https://github.com/greatscottgadgets/saturn-v/pull/3), so we plan to merge your tinyusb update (or its equivalent) and probably proceed further to tinyusb 0.15.0.

2023-06-30 10:07 UTC, mndza approved these changes
Thank you!

@mossmann This should be merged after #10

2023-07-06 10:01 UTC, merged