add support for Cynthion r1
greatscottgadgets/apollo pull request #16
Opened 2023-03-31 11:39 UTC by mossmann

The shared USB port (CONTROL) is now handed off to the FPGA at start-up (only on r1 for now). Press the PROGRAM button to have Apollo take over the port.

LED D now indicates that Apollo is using the shared USB port.

2023-06-20 08:44 UTC, mndza commented on firmware/src/boards/luna_d11/usb_switch.c
> +	gpio_set_pin_direction(FPGA_INT, GPIO_DIRECTION_IN);
`board_init()` in `lib/tinyusb/hw/bsp/samd11/family.c` is configuring another set of GPIO pins, including `BUTTON_PIN` (`PA16` regardless of the board revision).

I think we should either move the GPIO configuration lines to `board_init()` or create a new one somewhere else, and only keep the `gpio_get_pin_level()` calls here.

2023-07-17 03:13 UTC, Vangog7770 requested changes
- [ ] 1. ## ### **__**

2023-10-03 09:11 UTC, mndza commented on firmware/src/boards/cynthion_d11/usb_switch.c
> +	gpio_set_pin_direction(PROGRAM_BUTTON, GPIO_DIRECTION_IN);
This is no longer necessary, the GPIO is configured here:
https://github.com/hathach/tinyusb/blob/5b08a65ad2e695332d56bd4676841a91f34dd5b1/hw/bsp/samd11/family.c#L80-L81

2023-10-04 09:43 UTC, mndza approved these changes
:+1:

2023-10-06 01:44 UTC, merged