Update changelog for release 1.0.4
greatscottgadgets/apollo pull request #88
Opened 2024-06-26 15:03 UTC by mossmann

2024-06-26 15:07 UTC, mndza approved these changes

2024-06-26 15:10 UTC, antoinevg requested changes

2024-06-26 15:10 UTC, antoinevg commented on CHANGELOG.md
> +[1.0.4]: https://github.com/greatscottgadgets/apollo/compare/v1.0.2...v1.0.4
This should be:

```
[1.0.4]: https://github.com/greatscottgadgets/apollo/compare/v1.0.3...v1.0.4
```

2024-06-26 15:43 UTC, mossmann commented on CHANGELOG.md
> +[1.0.4]: https://github.com/greatscottgadgets/apollo/compare/v1.0.2...v1.0.4
Fixed, thank you!

2024-06-27 10:23 UTC, antoinevg approved these changes

2024-06-27 13:10 UTC, merged